name: testenv
channels:
  - conda-forge
  - defaults
dependencies:
  - arviz>=0.9
  - Cython
  - joblib
  - kiwisolver
  - matplotlib
  - patsy
  - pyparsing
  - python-dateutil
  - scipy
  - six
  - tqdm
  - cffi>=1.0.0
  - numba
  - tornado
  - numpy>=1.25
  - scipy>=0.18
  - pandas >=0.18
  - patsy>=0.5
  - h5py>=2.7
  - typing-extensions>=3.7
  - bokeh>=0.12
  - coverage>=5.1
  - python-graphviz
  - ipython>=7.16
  - nbsphinx>=0.4
  - nose>=1.3
  - nose-parameterized>=0.6
  - numpydoc>=0.9
  - pycodestyle>=2.3
  - pyflakes>=1.5
  - pylint>=1.7
  - pytest-cov>=2.5
  - pytest>=3.0
  - recommonmark>=0.4
  - scikit-learn>=0.20
  - seaborn>=0.8
  - sphinx-autobuild>=0.7
  - sphinx>=1.5
  - watermark
  - toyplot
  - parameterized
  - black
  - ipywidgets
  - dill
  